In [1]:
import numpy as np
from scipy.spatial.distance import cdist 
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances

In [2]:
df = pd.read_csv("20coordinate.csv")
# df = pd.read_csv("30 coordinates/30coordinate.csv")

In [3]:
df.head(2)

x   y
0  1  11
1  1   6

In [4]:
df.drop([7], axis=0, inplace=True)

In [5]:
df.head(2)

x   y
0  1  11
1  1   6

In [6]:
len(df)

19

In [7]:
np_df = df.to_numpy()

In [8]:
np_df

array([[ 1, 11],
       [ 1,  6],
       [ 3,  1],
       [ 6, -1],
       [ 3, -4],
       [ 3, -9],
       [ 9, -4],
       [11,  3],
       [11,  7],
       [11, 10],
       [ 4,  5],
       [15,  3],
       [15,  8],
       [15, -1],
       [15, -5],
       [13, -7],
       [12, -2],
       [ 9,  2],
       [ 8, -2]], dtype=int64)

In [9]:
len(np_df)

19

In [10]:
#Defining our function 
def kmeans(x,k, no_of_iterations):
    idx = np.random.choice(len(x), k, replace=False)
    #Randomly choosing Centroids 
    centroids = x[idx, :] #Step 1
     
    #finding the distance between centroids and all the data points
    distances = cdist(x, centroids ,'euclidean') #Step 2
     
    #Centroid with the minimum Distance
    points = np.array([np.argmin(i) for i in distances]) #Step 3
     
    #Repeating the above steps for a defined number of iterations
    #Step 4
    for _ in range(no_of_iterations): 
        centroids = []
        for idx in range(k):
            #Updating Centroids by taking mean of Cluster it belongs to
            temp_cent = x[points==idx].mean(axis=0) 
            centroids.append(temp_cent)
 
        centroids = np.vstack(centroids) #Updated Centroids 
         
        distances = cdist(x, centroids ,'euclidean')
        points = np.array([np.argmin(i) for i in distances])
    print(centroids)     
    return points  

In [11]:
#Applying our function
label = kmeans(np_df,3,100)

[[ 5.33333333 -3.16666667]
 [14.         -2.4       ]
 [ 7.875       6.5       ]]


In [12]:
label

array([2, 2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 2, 1, 1, 1, 1, 2, 0],
      dtype=int64)

In [13]:
[1, 1, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 3, 2, 3, 3, 3, 3, 0,
       0, 0, 0, 0, 0, 0, 3, 3]

[1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 3,
 2,
 3,
 3,
 3,
 3,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 3,
 3]

In [14]:
len(label)

19

In [15]:
df['clusters generated from manual implementation']=label

In [16]:
df

x   y  clusters generated from manual implementation
0    1  11                                              2
1    1   6                                              2
2    3   1                                              0
3    6  -1                                              0
4    3  -4                                              0
5    3  -9                                              0
6    9  -4                                              0
8   11   3                                              2
9   11   7                                              2
10  11  10                                              2
11   4   5                                              2
12  15   3                                              1
13  15   8                                              2
14  15  -1                                              1
15  15  -5                                              1
16  13  -7                                              1
17  12  -2                                              1
18   9   2                                              2
19   8  -2                                              0

In [17]:
len(df)

19

In [18]:
# df.to_excel("manual_kmeans_clusters.xlsx")

# Sklearn Implementation of KMeans Algorithm

In [19]:
from sklearn.cluster import KMeans

In [20]:
Cluster = KMeans(n_clusters=3)
Cluster.fit(np_df)
y_pred = Cluster.predict(np_df)

In [21]:
y_pred

array([1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 1, 2, 2, 2, 0, 0, 0, 2, 0])

In [22]:
len(y_pred)

19

In [23]:
Cluster.cluster_centers_

array([[ 8.625     , -4.25      ],
       [ 2.25      ,  5.75      ],
       [12.42857143,  4.57142857]])

In [24]:
Cluster.labels_

array([1, 1, 1, 0, 0, 0, 0, 2, 2, 2, 1, 2, 2, 2, 0, 0, 0, 2, 0])

In [25]:
df['Clusters generated from sklearn'] = y_pred

In [26]:
df.to_excel("kmeans_20_clusters.xlsx")