In [1]:
import numpy as np
from scipy.spatial.distance import cdist 
# from sklearn.cluster import KMeans
import pandas as pd
from sklearn.metrics.pairwise import euclidean_distances

In [2]:
df = pd.read_csv("30coordinate.csv")

In [3]:
df.head(2)

x  y
0  1  6
1  1  3

In [4]:
processing_element = 16
centroids = [8, 14, 19, 22]
centroids = [x-1 for x in centroids]

remove_nodes = centroids.copy()
remove_nodes.append(processing_element-1)
# remove_nodes = [x-1 for x in remove_nodes]
print(remove_nodes)
print(centroids)

[7, 13, 18, 21, 15]
[7, 13, 18, 21]


In [5]:
centroids_df = df.iloc[centroids]

In [6]:
centroids_df

x  y
7    5 -2
13   6  4
18  11 -3
21  11  4

In [7]:
cent_coords = centroids_df.to_numpy()
cent_coords

array([[ 5, -2],
       [ 6,  4],
       [11, -3],
       [11,  4]], dtype=int64)

In [8]:
cent_coords[0]

array([ 5, -2], dtype=int64)

In [9]:
df.drop(remove_nodes, axis=0, inplace=True)

In [10]:
df.head(2)

x  y
0  1  6
1  1  3

In [11]:
len(df)

25

In [12]:
np_df = df.to_numpy()

In [13]:
np_df

array([[ 1,  6],
       [ 1,  3],
       [ 2, -1],
       [ 2, -4],
       [ 1, -5],
       [ 1, -8],
       [ 5, -8],
       [ 3,  6],
       [ 4,  9],
       [ 2, 11],
       [ 6,  9],
       [ 6,  6],
       [ 7,  1],
       [ 7, -5],
       [12, -7],
       [10, -1],
       [10,  1],
       [ 9,  7],
       [11, 11],
       [13, 10],
       [13,  6],
       [16,  6],
       [15,  3],
       [15, -3],
       [15, -7]], dtype=int64)

In [14]:
len(np_df)

25

In [22]:
distances = euclidean_distances(cent_coords, np_df)

In [23]:
distances

array([[ 8.94427191,  6.40312424,  3.16227766,  3.60555128,  5.        ,
         7.21110255,  6.        ,  8.24621125, 11.04536102, 13.34166406,
        11.04536102,  8.06225775,  3.60555128,  3.60555128,  8.60232527,
         5.09901951,  5.83095189,  9.8488578 , 14.31782106, 14.4222051 ,
        11.3137085 , 13.60147051, 11.18033989, 10.04987562, 11.18033989],
       [ 5.38516481,  5.09901951,  6.40312424,  8.94427191, 10.29563014,
        13.        , 12.04159458,  3.60555128,  5.38516481,  8.06225775,
         5.        ,  2.        ,  3.16227766,  9.05538514, 12.52996409,
         6.40312424,  5.        ,  4.24264069,  8.60232527,  9.21954446,
         7.28010989, 10.19803903,  9.05538514, 11.40175425, 14.2126704 ],
       [13.45362405, 11.66190379,  9.21954446,  9.05538514, 10.19803903,
        11.18033989,  7.81024968, 12.04159458, 13.89244399, 16.64331698,
        13.        , 10.29563014,  5.65685425,  4.47213595,  4.12310563,
         2.23606798,  4.12310563, 10.19803903, 14

In [24]:
len(distances[0])

25

In [28]:
points = np.array([np.min(i) for i in distances])

In [29]:
points

array([3.16227766, 2.        , 2.23606798, 2.82842712])

In [27]:
np_df[points]

array([[ 2, -1],
       [ 6,  6],
       [10, -1],
       [13,  6]], dtype=int64)

In [21]:
clusters = {cent: [] for cent in centroids}
print(clusters)

{7: [], 13: [], 18: [], 21: []}


In [ ]:
for i in range(np_df):
    

In [ ]:
#Defining our function 
def kmeans(x,k, no_of_iterations):
    idx = np.random.choice(len(x), k, replace=False)
    #Randomly choosing Centroids 
    centroids = x[idx, :] #Step 1
     
    #finding the distance between centroids and all the data points
#     distances = cdist(x, centroids ,'euclidean') #Step 2
    distances = euclidean_distances(np_df, np_df)
    print(distances)
    #Centroid with the minimum Distance
    points = np.array([np.argmin(i) for i in distances]) #Step 3
     
    #Repeating the above steps for a defined number of iterations
    #Step 4
    for _ in range(no_of_iterations): 
        centroids = []
        for idx in range(k):
            #Updating Centroids by taking mean of Cluster it belongs to
            temp_cent = x[points==idx].mean(axis=0) 
            centroids.append(temp_cent)
 
        centroids = np.vstack(centroids) #Updated Centroids 
         
        distances = cdist(x, centroids ,'euclidean')
        points = np.array([np.argmin(i) for i in distances])
         
    return points 
 

In [ ]:
 
#Applying our function
label = kmeans(np_df,4,30)

In [ ]:
label

In [ ]:
label1 = kmeans(np_df,3,30)

In [ ]:
label1

In [ ]:
label2 = kmeans(np_df,4,50)

In [ ]:
label2

In [ ]:
label3 = kmeans(np_df,4,10)